using MediatR; using VetCommission.Application.Common.Errors; using VetCommission.Application.Common.Results; using VetCommission.Application.Features.Auth.Tenant;
namespace VetCommission.Application.Features.Clinics;
public sealed class ClinicHandlers(IClinicRepository repo, ITenantContext tenant) : IRequestHandler<ListClinicsQuery,NotificationResult<PagedResult<ClinicDto>>>,IRequestHandler<GetClinicQuery,NotificationResult<ClinicDto>>,IRequestHandler<SaveClinicCommand,NotificationResult<ClinicDto>>,IRequestHandler<SetClinicActiveCommand,NotificationResult<ClinicDto>>
{ public async Task<NotificationResult<PagedResult<ClinicDto>>> Handle(ListClinicsQuery r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<PagedResult<ClinicDto>>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):r.Page<1||r.PageSize<1||r.PageSize>100?NotificationResult<PagedResult<ClinicDto>>.Failure(new NotificationError(ErrorCodes.Validation,"Pagina ou tamanho invalidos.")):NotificationResult<PagedResult<ClinicDto>>.Success(await repo.ListAsync(t,r.Page,r.PageSize,r.Search,r.Active,c));
 public async Task<NotificationResult<ClinicDto>> Handle(GetClinicQuery r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<ClinicDto>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):await Result(repo.GetAsync(t,r.Id,c),"Clinica nao encontrada.");
 public async Task<NotificationResult<ClinicDto>> Handle(SaveClinicCommand r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<ClinicDto>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):await Result(repo.SaveAsync(t,r,c),"Clinica nao encontrada.");
 public async Task<NotificationResult<ClinicDto>> Handle(SetClinicActiveCommand r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<ClinicDto>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):await Result(repo.SetActiveAsync(t,r.Id,r.Active,c),"Clinica nao encontrada.");
 private static async Task<NotificationResult<ClinicDto>> Result(Task<ClinicDto?> t,string m){var v=await t;return v is null?NotificationResult<ClinicDto>.Failure(new NotificationError(ErrorCodes.NotFound,m)):NotificationResult<ClinicDto>.Success(v);}
}
