using MediatR; using VetCommission.Application.Common.Errors; using VetCommission.Application.Common.Results; using VetCommission.Application.Features.Auth.Tenant;
namespace VetCommission.Application.Features.ProfessionalRoles;
public sealed class ProfessionalRoleHandlers(IProfessionalRoleRepository repo, ITenantContext tenant) : IRequestHandler<ListProfessionalRolesQuery, NotificationResult<IReadOnlyCollection<ProfessionalRoleDto>>>, IRequestHandler<SaveProfessionalRoleCommand, NotificationResult<ProfessionalRoleDto>>, IRequestHandler<SetProfessionalRoleActiveCommand, NotificationResult<ProfessionalRoleDto>>
{
 public async Task<NotificationResult<IReadOnlyCollection<ProfessionalRoleDto>>> Handle(ListProfessionalRolesQuery r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<IReadOnlyCollection<ProfessionalRoleDto>>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):NotificationResult<IReadOnlyCollection<ProfessionalRoleDto>>.Success(await repo.ListAsync(t,c));
 public async Task<NotificationResult<ProfessionalRoleDto>> Handle(SaveProfessionalRoleCommand r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<ProfessionalRoleDto>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):await Result(repo.SaveAsync(t,r,c),"Funcao ou cargo nao encontrado.");
 public async Task<NotificationResult<ProfessionalRoleDto>> Handle(SetProfessionalRoleActiveCommand r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<ProfessionalRoleDto>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):await Result(repo.SetActiveAsync(t,r.Id,r.Active,c),"Funcao ou cargo nao encontrado.");
 private static async Task<NotificationResult<ProfessionalRoleDto>> Result(Task<ProfessionalRoleDto?> task,string message){var value=await task;return value is null?NotificationResult<ProfessionalRoleDto>.Failure(new NotificationError(ErrorCodes.NotFound,message)):NotificationResult<ProfessionalRoleDto>.Success(value);}
}
