using MediatR; using VetCommission.Application.Common.Errors; using VetCommission.Application.Common.Results; using VetCommission.Application.Features.Auth.Tenant;
namespace VetCommission.Application.Features.ProfessionalRoles;
public sealed class ProfessionalRoleHandlers(IProfessionalRoleRepository repo, ITenantContext tenant) : IRequestHandler<ListProfessionalRolesQuery, NotificationResult<PagedResult<ProfessionalRoleDto>>>, IRequestHandler<SaveProfessionalRoleCommand, NotificationResult<ProfessionalRoleDto>>, IRequestHandler<SetProfessionalRoleActiveCommand, NotificationResult<ProfessionalRoleDto>>
{
 public async Task<NotificationResult<PagedResult<ProfessionalRoleDto>>> Handle(ListProfessionalRolesQuery r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<PagedResult<ProfessionalRoleDto>>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):r.Page < 1 || r.PageSize is < 1 or > 100?NotificationResult<PagedResult<ProfessionalRoleDto>>.Failure(new NotificationError(ErrorCodes.Validation,"Pagina ou tamanho invalidos.")):NotificationResult<PagedResult<ProfessionalRoleDto>>.Success(await repo.ListAsync(t,r.Page,r.PageSize,c));
 public async Task<NotificationResult<ProfessionalRoleDto>> Handle(SaveProfessionalRoleCommand r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<ProfessionalRoleDto>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):await Result(repo.SaveAsync(t,r,c),"Funcao ou cargo nao encontrado.");
 public async Task<NotificationResult<ProfessionalRoleDto>> Handle(SetProfessionalRoleActiveCommand r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<ProfessionalRoleDto>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):await Result(repo.SetActiveAsync(t,r.Id,r.Active,c),"Funcao ou cargo nao encontrado.");
 private static async Task<NotificationResult<ProfessionalRoleDto>> Result(Task<ProfessionalRoleDto?> task,string message){var value=await task;return value is null?NotificationResult<ProfessionalRoleDto>.Failure(new NotificationError(ErrorCodes.NotFound,message)):NotificationResult<ProfessionalRoleDto>.Success(value);}
}
