using MediatR; using VetCommission.Application.Common.Errors; using VetCommission.Application.Common.Results; using VetCommission.Application.Features.Auth.Tenant;
namespace VetCommission.Application.Features.ProfessionalSpecialties;
public sealed class ProfessionalSpecialtyHandlers(IProfessionalSpecialtyRepository repo, ITenantContext tenant) : IRequestHandler<ListProfessionalSpecialtiesQuery, NotificationResult<IReadOnlyCollection<ProfessionalSpecialtyDto>>>, IRequestHandler<SaveProfessionalSpecialtyCommand, NotificationResult<ProfessionalSpecialtyDto>>, IRequestHandler<SetProfessionalSpecialtyActiveCommand, NotificationResult<ProfessionalSpecialtyDto>>
{
 public async Task<NotificationResult<IReadOnlyCollection<ProfessionalSpecialtyDto>>> Handle(ListProfessionalSpecialtiesQuery r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<IReadOnlyCollection<ProfessionalSpecialtyDto>>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):NotificationResult<IReadOnlyCollection<ProfessionalSpecialtyDto>>.Success(await repo.ListAsync(t,c));
 public async Task<NotificationResult<ProfessionalSpecialtyDto>> Handle(SaveProfessionalSpecialtyCommand r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<ProfessionalSpecialtyDto>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):await Result(repo.SaveAsync(t,r,c),"Especialidade nao encontrada.");
 public async Task<NotificationResult<ProfessionalSpecialtyDto>> Handle(SetProfessionalSpecialtyActiveCommand r,CancellationToken c)=>tenant.TenantId is not Guid t?NotificationResult<ProfessionalSpecialtyDto>.Failure(new NotificationError(ErrorCodes.Forbidden,"Tenant ativo obrigatorio.")):await Result(repo.SetActiveAsync(t,r.Id,r.Active,c),"Especialidade nao encontrada.");
 private static async Task<NotificationResult<ProfessionalSpecialtyDto>> Result(Task<ProfessionalSpecialtyDto?> task,string message){var value=await task;return value is null?NotificationResult<ProfessionalSpecialtyDto>.Failure(new NotificationError(ErrorCodes.NotFound,message)):NotificationResult<ProfessionalSpecialtyDto>.Success(value);}
}
