using FluentAssertions; using NSubstitute; using VetCommission.Application.Common.Errors; using VetCommission.Application.Common.Results; using VetCommission.Application.Features.Auth.Tenant; using VetCommission.Application.Features.ProcedureCategories;
namespace VetCommission.UnitTests.Application.ProcedureCategories;
public sealed class ProcedureCategoryHandlersTests
{
 [Fact] public async Task List_ShouldUseTenantAndClinic(){var t=Guid.NewGuid();var c=Guid.NewGuid();var repo=Substitute.For<IProcedureCategoryRepository>();repo.ListAsync(t,c,1,20,null,Arg.Any<CancellationToken>()).Returns(new PagedResult<ProcedureCategoryDto>([New(t,c)],1,20,1));var r=await new ProcedureCategoryHandlers(repo,new Tenant(t),new Clinic(c)).Handle(new ListProcedureCategoriesQuery(),CancellationToken.None);r.IsSuccess.Should().BeTrue();r.Value!.Items.Should().ContainSingle();await repo.Received(1).ListAsync(t,c,1,20,null,Arg.Any<CancellationToken>());}
 [Fact] public async Task List_ShouldRejectMissingClinic(){var r=await new ProcedureCategoryHandlers(Substitute.For<IProcedureCategoryRepository>(),new Tenant(Guid.NewGuid()),new Clinic(null)).Handle(new ListProcedureCategoriesQuery(),CancellationToken.None);r.IsFailure.Should().BeTrue();r.Errors.Should().ContainSingle(x=>x.Code==ErrorCodes.Forbidden);}
 [Fact] public async Task Save_ShouldReturnNotFoundWhenRepositoryReturnsNull(){var repo=Substitute.For<IProcedureCategoryRepository>();repo.SaveAsync(Arg.Any<Guid>(),Arg.Any<Guid>(),Arg.Any<SaveProcedureCategoryCommand>(),Arg.Any<CancellationToken>()).Returns((ProcedureCategoryDto?)null);var r=await new ProcedureCategoryHandlers(repo,new Tenant(Guid.NewGuid()),new Clinic(Guid.NewGuid())).Handle(new SaveProcedureCategoryCommand(null,"Consultas",null),CancellationToken.None);r.IsFailure.Should().BeTrue();r.Errors.Should().ContainSingle(x=>x.Code==ErrorCodes.NotFound);}
 private static ProcedureCategoryDto New(Guid t,Guid c)=>new(Guid.NewGuid(),t,c,"Consultas",null,true); private sealed class Tenant(Guid? id):ITenantContext{public Guid? TenantId=>id;} private sealed class Clinic(Guid? id):IClinicContext{public Guid? ClinicId=>id;}
}
