using Microsoft.EntityFrameworkCore; using VetCommission.Application.Common.Results; using VetCommission.Application.Features.Clinics; using VetCommission.Infrastructure.Persistence.Generated; using VetCommission.Infrastructure.Persistence.Generated.Entities;
namespace VetCommission.Infrastructure.Clinics;
public sealed class ClinicRepository(VetCommissionDbContext db):IClinicRepository
{ public async Task<PagedResult<ClinicDto>> ListAsync(Guid t,int p,int s,string? search,bool? active,CancellationToken c){var q=db.Clinics.AsNoTracking().Where(x=>x.TenantId==t);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Name.ToLower().Contains(search.Trim().ToLower()));if(active.HasValue)q=q.Where(x=>x.Active==active);var total=await q.CountAsync(c);var items=await q.OrderBy(x=>x.Name).ThenBy(x=>x.Id).Skip((p-1)*s).Take(s).Select(x=>new ClinicDto(x.Id,x.TenantId,x.Name,x.LegalName,x.Document,x.Email,x.Phone,x.Active,x.CreatedAtUtc,x.UpdatedAtUtc,x.InactivatedAtUtc)).ToArrayAsync(c);return new(items,p,s,total);}
 public Task<ClinicDto?> GetAsync(Guid t,Guid id,CancellationToken c)=>db.Clinics.AsNoTracking().Where(x=>x.TenantId==t&&x.Id==id).Select(x=>new ClinicDto(x.Id,x.TenantId,x.Name,x.LegalName,x.Document,x.Email,x.Phone,x.Active,x.CreatedAtUtc,x.UpdatedAtUtc,x.InactivatedAtUtc)).SingleOrDefaultAsync(c);
 public async Task<ClinicDto?> SaveAsync(Guid t,SaveClinicCommand c,CancellationToken ct){var e=c.Id is Guid id?await db.Clinics.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==id,ct):new Clinic{Id=Guid.NewGuid(),TenantId=t,Active=true,CreatedAtUtc=DateTime.UtcNow};if(e is null)return null;e.Name=c.Name.Trim();e.LegalName=Normalize(c.LegalName);e.Document=Normalize(c.Document);e.Email=Normalize(c.Email);e.Phone=Normalize(c.Phone);e.UpdatedAtUtc=DateTime.UtcNow;if(db.Entry(e).State==EntityState.Detached)db.Clinics.Add(e);await db.SaveChangesAsync(ct);return new(e.Id,e.TenantId,e.Name,e.LegalName,e.Document,e.Email,e.Phone,e.Active,e.CreatedAtUtc,e.UpdatedAtUtc,e.InactivatedAtUtc);}
 public async Task<ClinicDto?> SetActiveAsync(Guid t,Guid id,bool active,CancellationToken c){var e=await db.Clinics.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==id,c);if(e is null)return null;e.Active=active;e.InactivatedAtUtc=active?null:DateTime.UtcNow;e.UpdatedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync(c);return new(e.Id,e.TenantId,e.Name,e.LegalName,e.Document,e.Email,e.Phone,e.Active,e.CreatedAtUtc,e.UpdatedAtUtc,e.InactivatedAtUtc);}
 private static string? Normalize(string? v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();
}
