using Microsoft.EntityFrameworkCore; using VetCommission.Application.Common.Results; using VetCommission.Application.Features.ProcedureCategories; using VetCommission.Infrastructure.Persistence.Generated; using VetCommission.Infrastructure.Persistence.Generated.Entities;
namespace VetCommission.Infrastructure.Clinics;
public sealed class ProcedureCategoryRepository(VetCommissionDbContext db):IProcedureCategoryRepository
{
 public Task<ProcedureCategoryDto?> GetAsync(Guid t,Guid c,Guid id,CancellationToken ct)=>db.ProcedureCategories.AsNoTracking().Where(x=>x.TenantId==t&&x.ClinicId==c&&x.Id==id).Select(x=>new ProcedureCategoryDto(x.Id,x.TenantId,x.ClinicId,x.Name,x.Description,x.Active)).SingleOrDefaultAsync(ct);
 public async Task<PagedResult<ProcedureCategoryDto>> ListAsync(Guid t,Guid c,int p,int s,string? search,CancellationToken ct){var q=db.ProcedureCategories.AsNoTracking().Where(x=>x.TenantId==t&&x.ClinicId==c);var n=await q.CountAsync(ct);var i=await q.OrderBy(x=>x.Name).Skip((p-1)*s).Take(s).Select(x=>new ProcedureCategoryDto(x.Id,x.TenantId,x.ClinicId,x.Name,x.Description,x.Active)).ToArrayAsync(ct);return new(i,p,s,n);}
 public async Task<ProcedureCategoryDto?> SaveAsync(Guid t,Guid c,SaveProcedureCategoryCommand v,CancellationToken ct){var e=v.Id is Guid id?await db.ProcedureCategories.SingleOrDefaultAsync(x=>x.TenantId==t&&x.ClinicId==c&&x.Id==id,ct):new ProcedureCategory{Id=Guid.NewGuid(),TenantId=t,ClinicId=c,Active=true,CreatedAtUtc=DateTime.UtcNow};if(e is null)return null;e.Name=v.Name.Trim();e.Description=string.IsNullOrWhiteSpace(v.Description)?null:v.Description.Trim();e.UpdatedAtUtc=DateTime.UtcNow;if(db.Entry(e).State==EntityState.Detached)db.ProcedureCategories.Add(e);await db.SaveChangesAsync(ct);return new(e.Id,e.TenantId,e.ClinicId,e.Name,e.Description,e.Active);}
 public async Task<ProcedureCategoryDto?> SetActiveAsync(Guid t,Guid c,Guid id,bool active,CancellationToken ct){var e=await db.ProcedureCategories.SingleOrDefaultAsync(x=>x.TenantId==t&&x.ClinicId==c&&x.Id==id,ct);if(e is null)return null;e.Active=active;e.InactivatedAtUtc=active?null:DateTime.UtcNow;e.UpdatedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync(ct);return new(e.Id,e.TenantId,e.ClinicId,e.Name,e.Description,e.Active);}
}
